---
- hosts: all
  become: true
  tasks:

  - name: update apt index
    ansible.buildin.apt:
      update_cache: yes

  - name: install apache2
    ansible.buildin.apt:
      name: apache2
      state: latest

  - name: install support for php
    ansible.buildin.apt:
      name: libapache2-mod-php
      state: latest
