---
- hosts: all
  become: true
  tasks:

  - name: update apt index
    ansible.buildin.apt:
      update_cache: yes

  - name: remove apache2
    ansible.buildin.apt:
      name: apache2
      state: absent

  - name: remove support for php
    ansible.buildin.apt:
      name: libapache2-mod-php
      state: absent
